services:
  - type: web
    name: trustwipe-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/trustwipe-0.0.1-SNAPSHOT.jar
    rootDirectory: trustwipe-backend
    envVars:
      - key: PORT
        value: 8081
      - key: MONGODB_URI
        value: mongodb+srv://Mayank:Mayank%40123@cluster0.yckoeig.mongodb.net/trustwipe?retryWrites=true&w=majority
