services:
  - type: web
    name: trustwipe-backend
    env: docker
    rootDir: trustwipe-backend
    envVars:
      - key: PORT
        value: 8081
      - key: MONGODB_URI
        value: mongodb+srv://Mayank:Mayank%40123@cluster0.yckoeig.mongodb.net/trustwipe?retryWrites=true&w=majority
