# MongoDB Atlas Connection (Production Cloud)
spring.data.mongodb.uri=mongodb+srv://Mayank:Mayank%40123@cluster0.yckoeig.mongodb.net/trustwipe?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
server.port=${PORT:8081}
